### ISSUE TITLE
command aliases

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rackcli#10]
We can provide aliases for commands like `ls` for `list` easily enough. The question is if we want to or not. Off the top of my head, the only reason I can think not to would be that when using bash completion, the options available could be large. For example, with aliases, if I typed `rackcli compute servers [tab]`, I might see something like:
`mk create update get ls list delete rm`
as opposed to
`create update get delete list`.

Not really a big difference, but users may wonder if there's a difference between, say, `ls` and `list`.

**Comment by jnoller** [comment]
Instead of aliases, let's go with the list (long/descriptive) system over the unixy style - this way it's less surprising for users on windows / newbies

**Comment by jrperritt** [comment]
:+1:
