### ISSUE TITLE
command format

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rackcli#6]
Currently, the format is:
```<cliName> <service> <subservice> <action> <flags>```
Example: ```rackcli compute servers list --name server1```

Personally, I prefer being explicit like above. However, I know some people prefer terse commands:

```<cliName> <subservice> <action> <flags>```
Example: ```rackcli servers list --name server1```

Though it's true that in the above example removing the service leaves no ambiguity, there are services like load balancers where you'd have `rackcli members list <lbID>`. It's not obvious that the command is for listing members of a load balancer and though we could have something like `rackcli lb-members list <lbID>`, that seems to lack consistency.

With bash completion for commands (and in time, flags), I don't think being explicit is much of an inconvenience, but I'd like to hear what others think.

**Comment by jnoller** [comment]
I definitely like https://cloud.google.com/compute/docs/gcloud-compute/#creating formatting

**Comment by jrperritt** [comment]
Yeah, me too.
